name: MYCI
# on: [push]
# push 和 schedule 二选一
on:
  push:
    branches:
      - master
    # paths:
    #   - src/* # src下的任何文件变动
    # schedule:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 # 拷贝代码
      - run: |
          node -v